# Generated by Django 2.1.7 on 2019-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='end_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
