# Generated by Django 2.1.7 on 2019-03-27 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20190327_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 27, 0, 0)),
            preserve_default=False,
        ),
    ]
