# Generated by Django 2.1.7 on 2019-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20190327_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='color',
            field=models.CharField(choices=[('NON', 'None'), ('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('YLW', 'Yellow')], default='NON', max_length=3),
        ),
    ]
