# Generated by Django 2.1.7 on 2019-04-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='color',
            field=models.CharField(choices=[('none', 'None'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], default='NON', max_length=3),
        ),
    ]
