# Generated by Django 2.1.7 on 2019-04-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20190405_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='color',
            field=models.CharField(choices=[('none', 'None'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], default='none', max_length=3),
        ),
    ]
