# Generated by Django 2.1.7 on 2019-04-06 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_accountpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpreferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
