# Generated by Django 2.1.7 on 2019-04-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_auto_20190406_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpreferences',
            name='monthly_expense_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
